-- Per-job cleaning checklist (app expects this table; lister + assigned cleaner read/write).
-- Apply in Supabase SQL Editor if the table is missing in production.

CREATE TABLE IF NOT EXISTS public.job_checklist_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id integer NOT NULL REFERENCES public.jobs (id) ON DELETE CASCADE,
  label text NOT NULL,
  is_completed boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_job_checklist_items_job_id
  ON public.job_checklist_items (job_id);

COMMENT ON TABLE public.job_checklist_items IS
  'Per-job cleaning checklist rows; seeded when job moves to in_progress.';

ALTER TABLE public.job_checklist_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "job_checklist_items_select_parties" ON public.job_checklist_items;
CREATE POLICY "job_checklist_items_select_parties"
  ON public.job_checklist_items FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.jobs j
      WHERE j.id = job_checklist_items.job_id
        AND (j.lister_id = auth.uid() OR j.winner_id = auth.uid())
    )
  );

DROP POLICY IF EXISTS "job_checklist_items_select_admin" ON public.job_checklist_items;
CREATE POLICY "job_checklist_items_select_admin"
  ON public.job_checklist_items FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid()
        AND lower(trim(COALESCE(p.is_admin::text, ''))) IN ('true', 't', '1', 'yes')
    )
  );

DROP POLICY IF EXISTS "job_checklist_items_insert_parties" ON public.job_checklist_items;
CREATE POLICY "job_checklist_items_insert_parties"
  ON public.job_checklist_items FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.jobs j
      WHERE j.id = job_checklist_items.job_id
        AND (j.lister_id = auth.uid() OR j.winner_id = auth.uid())
    )
  );

DROP POLICY IF EXISTS "job_checklist_items_update_parties" ON public.job_checklist_items;
CREATE POLICY "job_checklist_items_update_parties"
  ON public.job_checklist_items FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.jobs j
      WHERE j.id = job_checklist_items.job_id
        AND (j.lister_id = auth.uid() OR j.winner_id = auth.uid())
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.jobs j
      WHERE j.id = job_checklist_items.job_id
        AND (j.lister_id = auth.uid() OR j.winner_id = auth.uid())
    )
  );
