-- Notifications table and RLS for realtime in-app notifications.
-- Run in Supabase SQL editor. If the table already exists, run only the RLS and type-alter sections.

-- 1. Create table (skip if you already have notifications with compatible schema)
CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type text NOT NULL CHECK (type IN (
    'new_message', 'job_created', 'job_accepted', 'job_completed',
    'dispute_opened', 'payment_released', 'new_bid',
    'dispute_resolved', 'funds_ready'
  )),
  job_id bigint REFERENCES public.jobs(id) ON DELETE SET NULL,
  message_text text NOT NULL,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON public.notifications (user_id, is_read) WHERE is_read = false;
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON public.notifications (created_at DESC);

-- 2. RLS
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own notifications" ON public.notifications;
CREATE POLICY "Users can read own notifications" ON public.notifications
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own notifications (mark read)" ON public.notifications;
CREATE POLICY "Users can update own notifications (mark read)" ON public.notifications
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Insert: only backend (service role or trusted server) creates rows; restrict direct insert from anon
-- If your app inserts via server action with createServerSupabaseClient(), the session is the actor.
-- To allow server-side insert as "on behalf of" another user, use service role or a trigger.
DROP POLICY IF EXISTS "Service role or same user insert" ON public.notifications;
-- Allow insert when user_id = auth.uid() (e.g. self-notify) OR rely on service role for cross-user
CREATE POLICY "Service role or same user insert" ON public.notifications
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Enable realtime for notifications (Supabase Dashboard > Database > Replication > enable for notifications)
-- Or: publication supabase_realtime should include notifications table.

COMMENT ON TABLE public.notifications IS 'In-app notifications; subscribe via realtime for live updates.';
