-- Review system hardening and compatibility updates

CREATE TABLE IF NOT EXISTS public.reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id bigint NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  reviewer_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  reviewee_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  reviewee_role text,
  reviewee_type text,
  overall_rating integer NOT NULL,
  quality_of_work integer,
  reliability integer,
  communication integer,
  punctuality integer,
  review_text text,
  review_photos text[],
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.reviews
  ADD COLUMN IF NOT EXISTS reviewee_role text,
  ADD COLUMN IF NOT EXISTS reviewee_type text,
  ADD COLUMN IF NOT EXISTS overall_rating integer,
  ADD COLUMN IF NOT EXISTS quality_of_work integer,
  ADD COLUMN IF NOT EXISTS reliability integer,
  ADD COLUMN IF NOT EXISTS communication integer,
  ADD COLUMN IF NOT EXISTS punctuality integer,
  ADD COLUMN IF NOT EXISTS review_text text,
  ADD COLUMN IF NOT EXISTS review_photos text[],
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

UPDATE public.reviews
SET reviewee_role = COALESCE(reviewee_role, reviewee_type)
WHERE reviewee_role IS NULL;

UPDATE public.reviews
SET reviewee_type = COALESCE(reviewee_type, reviewee_role)
WHERE reviewee_type IS NULL;

ALTER TABLE public.reviews
  ADD CONSTRAINT reviews_reviewee_role_check
    CHECK (reviewee_role IN ('cleaner', 'lister')) NOT VALID;

ALTER TABLE public.reviews
  ADD CONSTRAINT reviews_reviewee_type_check
    CHECK (reviewee_type IN ('cleaner', 'lister')) NOT VALID;

ALTER TABLE public.reviews
  ADD CONSTRAINT reviews_overall_rating_check
    CHECK (overall_rating BETWEEN 1 AND 5) NOT VALID;

ALTER TABLE public.reviews
  ADD CONSTRAINT reviews_review_text_len_check
    CHECK (review_text IS NULL OR char_length(review_text) <= 1000) NOT VALID;

CREATE UNIQUE INDEX IF NOT EXISTS reviews_job_reviewer_reviewee_unique_idx
  ON public.reviews(job_id, reviewer_id, COALESCE(reviewee_type, reviewee_role));

CREATE INDEX IF NOT EXISTS reviews_reviewee_idx
  ON public.reviews(reviewee_id, COALESCE(reviewee_type, reviewee_role), created_at DESC);

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS review_count integer NOT NULL DEFAULT 0;

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "reviews_insert_own_reviewer" ON public.reviews;
CREATE POLICY "reviews_insert_own_reviewer"
  ON public.reviews
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = reviewer_id);

DROP POLICY IF EXISTS "reviews_select_participants_and_admin" ON public.reviews;
CREATE POLICY "reviews_select_participants_and_admin"
  ON public.reviews
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.jobs j
      WHERE j.id = reviews.job_id
        AND (j.lister_id = auth.uid() OR j.winner_id = auth.uid())
    )
    OR EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid() AND p.is_admin = true
    )
  );

